### PR TITLE
fix: do not use aiolimiter.compat 

### PR DESCRIPTION
**Pull request by NTFSvolume**
1. `compat` module was deprecated on v1.1.1. We need to switch to the standard `asyncio.wait_for`
2. Remove unused `mutagen` dependency
3. Remove unused `pyreadline3` dependency

- Related to #358

### CODE REVIEW

**Comment by datawhores** [comment]
Where you able to make sure the speed limit still works with this change?

**Comment by Internal-Compiler-Error** [comment]
FWIW, I had a fresh install via `pipx` yesterday and the `aiolimiter` it came with was 1.2.1 instead of `1.1.1` as indicated in the poetry lock files, and the API has already been removed by that point. I fixed it by manually injecting `aiolimiter==1.1.1` into it

**Comment by NTFSvolume** [comment]
Simplified the speed limiter logic and tested it. It's working as expected

**Comment by datawhores** [comment]
Awesome that should make it a lot easier to update in he future

**Review by datawhores — APPROVED** [review]

**Pull request merged**
