### PR TITLE
ci: add ruff as linter and formatter + pre-commit hooks

### PR DESCRIPTION
**Pull request by NTFSvolume**
This PR is a proposal to integrate [ruff ](https://github.com/astral-sh/ruff) as a linter and auto formatter for the entire repo, to minimize `git diff` on new commits, use a standard style and remove the necessity for future PRs that are just reformats

> [!CAUTION]
> This PR will highlight a ***bunch of issues*** in the entire codebase and will prevent any new commits from being made until those issues are fixed. It will also ***break basically every branch*** after the issues are fixed cause it will be practically impossible to rebase from master. They will require a manual (***huge***) merge conflict resolution. However, it will only need to be done once and `ruff` will handle any new commits in the future.

I will create a new PR with all the necessary fixes after this PR is merged. This PR is mostly just to reach an agreement about ruff implementation, and the rules definition that it will use to check new commits and auto fix them when possible.

I put some standard lint rules in the config.  Rules can always be added later on, or removed if they are found to be too restrictive

Even if approved, the merge of this PR can be postponed until other currently working-on branches are merged to master, to reduce merge conflicts.

### CODE REVIEW

**Comment by jbsparrow** [comment]
For the caching branch it might be better to just start it from scratch. It has so many differences compared to master but most of them are useless or things that are implemented in better ways on the master branch.

The actual caching stuff is really simple. We have a few functions in the cache manager to set it up and decide how to filter certain things and we replace most instances of `aiohttp.ClientSession` with `aiohttp_client_cache.CachedSession`.

I can't think of any huge differences that would be difficult to re-implement by just resetting the caching branch from master.

We can also merge max_scrape_children into master before merging this.

**Comment by NTFSvolume** [comment]
Agree. I also have some branches i want to merge but it will be easier to just re-do them. Let's wait until @datawhores approves cause they may be working on something that they may want to merge before this PR.

**Review by datawhores — APPROVED** [review]

**Comment by datawhores** [comment]
I don't have anything right now

**Review by jbsparrow — APPROVED** [review]

**Comment by jbsparrow** [comment]
I think we're good to merge it now

**Comment by NTFSvolume** [comment]
Let's wait until 5.7.1 is tested for a bit and do a stable release before merging this

**Pull request merged**
