### PR TITLE
Pixeldrain text scraping

### PR DESCRIPTION
**Pull request by jbsparrow**
Implement the ability to scrape URLs from a PixelDrain text post and make them their own folder instead of various folders for each URL in the list.

### CODE REVIEW

**Comment by jbsparrow** [comment]
I did some more testing and this isn't done yet 😿

**Comment by jbsparrow** [comment]
Resolved the issue, ready to merge.

**Comment by datawhores** [comment]
This still works for images and video?

**Comment by jbsparrow** [comment]
> This still works for images and video?

Yep, still works for images and videos. The reason I put the check for plaintext first is because of a flaw in the logic which I have since resolved, but just haven't reversed the orders.

The order isn't really all that relevant though 🤷‍♂️

**Review by datawhores — APPROVED** [review]

**Pull request merged**
