### PR TITLE
Fix Coomer & Kemono to work with new API

### PR DESCRIPTION
**Pull request by jbsparrow**
This PR uses the new Coomer & Kemono APIs to get profile information. It also simplifies four functions into one that serves the same purpose.

### CODE REVIEW

**Review by NTFSvolume — CHANGES_REQUESTED** [review]
Drop the last commit and then force push. 

For this PR ignore the ruff errors on any file that is not the crawlers, to prevent merge conflicts with master

**Comment by jbsparrow** [comment]
Sounds good. I was thinking I should also just release this as 5.7.3 before merging into master because we need to finish tests on the stuff on master.

**Comment by NTFSvolume** [comment]
That's fine. I will merge the bunkr PR into this first so it gets included in 5.7.3 as well

**Review by NTFSvolume — APPROVED** [review]

**Comment by NTFSvolume** [comment]
You have to push the update manually to pypi from this branch cause the gh-action only works on the master branch

**Pull request merged**
