### PR TITLE
fix: asyncio lock fixes

### PR DESCRIPTION
**Pull request by NTFSvolume**
1. Use a contextmanager for all asyncio locks. Fixes `Ctrl + C` not working in some cases
2. Catch the base `aiohttp.ClientError` exception to handle all possible connection errors, including DNS lookups errors
3. Use a single `error_handle_wrapper` for both scraping and downloading

### CODE REVIEW

**Comment by datawhores** [comment]
Could the ratelimit options be moved to pydantic so it's a hard limit
Otherwise I think it is only checked one

def adjust_for_simpcity(self) -> None:
        """Adjusts settings for SimpCity update."""
       ..........
            rate_limit_options = self.config_manager.global_settings_data.rate_limiting_options
            if rate_limit_options.download_attempts >= 10:
                rate_limit_options.download_attempts = 5
            if rate_limit_options.max_simultaneous_downloads_per_domain > 15:
                rate_limit_options.max_simultaneous_downloads_per_domain = 5

**Comment by NTFSvolume** [comment]
I think is intentional to only do it once.

**Comment by NTFSvolume** [comment]
`temp_table` is no longer used for anything. I will remove it

**Comment by NTFSvolume** [comment]
This also includes the fix for the semaphore only allowing 1 download per crawler

**Comment by jbsparrow** [comment]
> I think is intentional to only do it once.

Yeah, I don't want to limit people too much on that stuff. Just do it the first time and if they don't change it back they probably didn't have a reason to have it that high anyways.

**Review by jbsparrow — APPROVED** [review]
Code looks all good, we can merge and do some testing with it.

**Pull request merged**
