### PR TITLE
Update changelog for real-debrid.

### PR DESCRIPTION
**Pull request by jbsparrow**
Include real-debrid support in changelog

### CODE REVIEW

**Review by NTFSvolume — CHANGES_REQUESTED** [review]
RealDebrid would be part of 5.7.1 cause 5.7.0 was released already.

**Comment by jbsparrow** [comment]
I didn't know that we released 5.7.0 yet. Will update the changelog to reflect that.

**Comment by jbsparrow** [comment]
Will wait for csv logs before pushing 5.7.1 to pypi

**Review by NTFSvolume — APPROVED** [review]
Did not merge cause I'm not sure if it will automatically publish to PyPI

**Pull request merged**
